project:
  type: website
  output-dir: docs
  execute-dir: project
  render:
    - "*.qmd"
    - "!README.md"

website:
  title: "TreeDì-P1G - TSQ Structural data protocol"
  navbar:
    left:
      - href: data_protocol.qmd
        text: Data protocol
      - href: structural_analysis.qmd
        text: Analysis Pipeline
      - href: figures.qmd
        text: Structural Plots
    right: 
      - icon: github
        href: https://github.com/ataeub/treedi-tsq-structure-pipeline

format:
  html:
    theme: minty
